name:                drive-slack
version:             0.1.0.0
github:              "palf/test-drive"
license:             BSD3
author:              "Jack Palfrey"
maintainer:          "jack.palf@gmail.com"
copyright:           "2019 Jack Palfrey"

description:         Please see the README on Github at <https://github.com/palf/test-drive#readme>

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - drive-base
  - drive-describe

library:
  source-dirs: lib
  exposed-modules:
    - Drive.Slack
  dependencies:
    - free
    - text
    - yaml
    - slack-web
    - mtl

executables:
  example-drive-slack:
    main: Main.hs
    source-dirs: src
    dependencies:
      - drive-slack
      - mtl
      - text
    ghc-options: -Wall -threaded -rtsopts -with-rtsopts=-N

