resolver: lts-13.10

packages:
  - packages/drive-base
  - packages/drive-describe
  - packages/drive-terminal
  - packages/drive-file
  - packages/drive-http
  - packages/drive-browser
  # - packages/drive-intercom
  - packages/drive-trello
  - packages/drive-slack
  - apps/trello-terminal
