name:                drive-base
version:             0.1.0.0
github:              "palf/test-drive"
license:             BSD3
author:              "Jack Palfrey"
maintainer:          "jack.palf@gmail.com"
copyright:           "2019 Jack Palfrey"

description:         Please see the README on Github at <https://github.com/palf/test-drive#readme>

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs:      lib
  exposed-modules:
    - Drive
  dependencies:
    - free
    - transformers
    - mtl
