name:                drive-terminal
version:             0.1.0.0
github:              "palf/test-drive"
license:             BSD3
author:              "Jack Palfrey"
maintainer:          "jack.palf@gmail.com"
copyright:           "2019 Jack Palfrey"

description:         Please see the README on Github at <https://github.com/palf/test-drive#readme>

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - drive-base
  - drive-describe
  - text

library:
  source-dirs: lib
  exposed-modules:
    - Drive.Terminal
  dependencies:
    - free

executables:
  example-drive-terminal:
    main: Main.hs
    source-dirs: src
    dependencies:
      - drive-terminal
    ghc-options: -Wall -threaded -rtsopts -with-rtsopts=-N
